// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createUser.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	return err
}
