// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getClientByID.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, allowed_redirect_uris FROM clients WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(&i.ID, &i.Name, &i.AllowedRedirectUris)
	return i, err
}
