// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID                  uuid.UUID
	Name                string
	AllowedRedirectUris []string
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    pgtype.Timestamptz
}
